apiVersion: v1
kind: Service
metadata:
  name: django-blog
  namespace: "{{ ns }}"
spec:
  selector:
    role: blog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 32000
  type: NodePort
